// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IiMSAl0JgG2wc2UxL_BXyIQCdb_HoQE',
    appId: '1:424381619205:web:1ed6e8e721b15cd456106c',
    messagingSenderId: '424381619205',
    projectId: 'skilltree-6f76c',
    authDomain: 'skilltree-6f76c.firebaseapp.com',
    storageBucket: 'skilltree-6f76c.appspot.com',
    measurementId: 'G-4D01R6T64Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWbIP3UCyeCr3w3rGDMEXgfHlfrgZXj0',
    appId: '1:424381619205:android:838fffdcc937333456106c',
    messagingSenderId: '424381619205',
    projectId: 'skilltree-6f76c',
    storageBucket: 'skilltree-6f76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfG2QMFBZ18EgxSJ_gZVQ8EqFwyyQ8MZ4',
    appId: '1:424381619205:ios:262504a59047b75356106c',
    messagingSenderId: '424381619205',
    projectId: 'skilltree-6f76c',
    storageBucket: 'skilltree-6f76c.appspot.com',
    iosClientId: '424381619205-07k4vsfuldqp3hic2r65gjq448j0paiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilltreeApp',
  );
}
